trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  patch: $[counter('VersionCounter', 0)]
  buildConfiguration: 'Release'

name: 0.$(patch)

steps:
- task: PowerShell@2
  displayName: Update manifest file version
  inputs:
    filePath: 'build\update-version.ps1'
    arguments: '$(Build.BuildNumber)'
    pwsh: true

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'

- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    platform: 'any cpu'
    configuration: $(buildConfiguration)
    clean: false

- task: CopyFiles@2
  inputs:
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github.com_fxredeemer'
    repositoryName: 'fxredeemer/TemplateApp'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'gitTag'
    tagPattern: 'v$(MajorVersion).$(MinorVersion).$(PatchVersion)'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'